const app = document.querySelector('.app');
const page = document.body.dataset.page;
const iconPaths = {
  play:'<path d="m9 5 11 7-11 7z" fill="currentColor" stroke="none"/>',
  stop:'<rect x="6" y="6" width="12" height="12" rx="1" fill="currentColor" stroke="none"/>',
  metro:'<path d="m9 3-5 18h16L15 3M12 14l7-8M8 17h8"/>',
  train:'<path d="M3 17V7m6 13V4m6 13V7m6 13V4"/>',
  settings:'<path d="M4 7h9m4 0h3M4 17h3m4 0h9"/><circle cx="15" cy="7" r="2"/><circle cx="9" cy="17" r="2"/>',
  expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',
  back:'<path d="m14 5-7 7 7 7"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  sound:'<path d="m11 5-6 4H2v6h3l6 4zM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
  tap:'<path d="M9 12V5a2 2 0 0 1 4 0v6l1-1a2 2 0 0 1 3 1 2 2 0 0 1 3 2v4l-3 4h-6l-6-6a2 2 0 0 1 3-3l1 1M5 3 3 5m13-2 2 2"/>',
  rhythm:'<path d="M6 5v14M12 5v14M18 5v14"/><circle cx="6" cy="9" r="2" fill="currentColor"/><circle cx="12" cy="15" r="2" fill="currentColor"/><circle cx="18" cy="9" r="2" fill="currentColor"/>',
  lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 4v3"/>',
  check:'<path d="m5 12 4 4L19 6"/>'
};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||iconPaths.arrow}</svg>`;}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let bpm=120,playing=false,beat=0,timer=null,taps=[],locked=false,toastTimer;
const filenames={instrument:'01-instrument.html',rhythm:'02-rhythm.html',training:'03-training.html',sound:'04-sound.html',kit:'05-kit-view.html',creator:'06-creator-edition.html'};
function navigate(id){const selectedEdition=page==='creator'?edition:new URLSearchParams(location.search).get('edition');if(window.parent!==window){window.parent.postMessage({type:'audit-navigate',page:id,edition:selectedEdition},'*');}else{window.location.href=filenames[id]+(selectedEdition?'?edition='+encodeURIComponent(selectedEdition):'');}}
function toast(text){const el=document.querySelector('.toast');el.textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.textContent='',2600);}
function setTempo(value){bpm=Math.max(20,Math.min(300,Math.round(Number(value)||120)));document.querySelectorAll('[data-bpm]').forEach(el=>{if(el.tagName==='INPUT')el.value=bpm;else el.textContent=bpm;});if(playing){clearInterval(timer);timer=setInterval(pulse,60000/bpm);}}
function pulse(){document.querySelectorAll('[data-beat]').forEach(el=>el.classList.toggle('lit',Number(el.dataset.beat)===beat));beat=(beat+1)%4;}
function setPlaying(value){playing=value;document.querySelectorAll('[data-transport-state]').forEach(el=>el.textContent=playing?'Playing':'Ready');clearInterval(timer);document.querySelectorAll('[data-play]').forEach(el=>{el.innerHTML=icon(playing?'stop':'play')+(el.classList.contains('primary')?`<span>${playing?'Stop':'Start'}</span>`:'');el.setAttribute('aria-label',playing?'Stop metronome':'Start metronome');el.setAttribute('aria-pressed',String(playing));});document.querySelectorAll('[data-status]').forEach(el=>{el.innerHTML=`<span class="status-dot"></span>${playing?'Playing':'Ready'}`;el.classList.toggle('playing',playing);});if(playing){pulse();timer=setInterval(pulse,60000/bpm);}else{beat=0;document.querySelectorAll('[data-beat]').forEach(el=>el.classList.toggle('lit',Number(el.dataset.beat)===0));}}
document.addEventListener('click',async event=>{
 const nav=event.target.closest('[data-go]');if(nav){navigate(nav.dataset.go);return;}
 const play=event.target.closest('[data-play]');if(play){setPlaying(!playing);return;}
 const nudge=event.target.closest('[data-nudge]');if(nudge){setTempo(bpm+Number(nudge.dataset.nudge));return;}
 if(event.target.closest('[data-tap]')){const t=performance.now();if(taps.length&&t-taps.at(-1)>2000)taps=[];taps.push(t);taps=taps.slice(-6);const output=document.querySelector('[data-tap-status]');if(taps.length>=4){setTempo(60000/((taps.at(-1)-taps[0])/(taps.length-1)));output.textContent=`${bpm} BPM · keep tapping`;}else output.textContent=`${taps.length} of 4 taps`;return;}
 const mode=event.target.closest('[data-mode]');if(mode){document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el===mode)));document.querySelectorAll('[data-mode-panel]').forEach(el=>el.hidden=el.dataset.modePanel!==mode.dataset.mode);return;}
 const sub=event.target.closest('[data-subdivision]');if(sub){subdivision=Number(sub.dataset.subdivision);updateSubdivision();return;}
 const acc=event.target.closest('.accent-cell');if(acc){const states=['off','on','accent'];acc.dataset.state=states[(states.indexOf(acc.dataset.state)+1)%3];acc.setAttribute('aria-label',`${acc.dataset.label}: ${acc.dataset.state}. Tap to change.`);return;}
 const beats=event.target.closest('[data-beats-change]');if(beats){beatsPerBar=Math.max(1,Math.min(16,beatsPerBar+Number(beats.dataset.beatsChange)));document.querySelector('[data-beats-count]').textContent=beatsPerBar;renderAccentGrid();return;}
 if(event.target.closest('[data-apply-rhythm]')){toast('Rhythm applied to this design preview.');return;}
 const toggle=event.target.closest('[data-trainer]');if(toggle){const on=toggle.getAttribute('aria-checked')!=='true';toggle.setAttribute('aria-checked',String(on));document.querySelector(`[data-config="${toggle.dataset.trainer}"]`).hidden=!on;updateTrainingStatus();return;}
 const sound=event.target.closest('[data-sound]');if(sound){document.querySelectorAll('[data-sound]').forEach(el=>el.setAttribute('aria-checked',String(el===sound)));document.querySelector('[data-sound-status]').textContent=`${sound.dataset.sound} selected`;document.querySelector('[data-selected-sound]').textContent=sound.dataset.sound;return;}
 const preview=event.target.closest('[data-preview]');if(preview){await previewSound(preview.dataset.preview);return;}
 const lock=event.target.closest('[data-lock]');if(lock){locked=!locked;lock.setAttribute('aria-pressed',String(locked));lock.innerHTML=icon('lock')+(locked?'Unlock tempo':'Lock tempo');document.querySelectorAll('[data-nudge]').forEach(el=>el.disabled=locked);document.querySelector('[data-lock-note]').textContent=locked?'Tempo locked. Stop is always available.':'Lock tempo to prevent accidental changes.';return;}
 if(event.target.closest('[data-enter-pack]')){showCreator('pack');return;}
 if(event.target.closest('[data-creator-back]')){showCreator('pack');setPlaying(false);return;}
 const lesson=event.target.closest('[data-lesson]');if(lesson){openLesson(Number(lesson.dataset.lesson));return;}
});
document.querySelectorAll('[data-bpm]').forEach(el=>{if(el.tagName==='INPUT')el.addEventListener(el.type==='range'?'input':'change',()=>setTempo(el.value));});
document.querySelectorAll('input.tempo-number').forEach(el=>el.addEventListener('focus',()=>el.select()));
document.addEventListener('keydown',event=>{if(event.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(event.target.tagName)){event.preventDefault();setPlaying(!playing);}});
document.addEventListener('keydown',event=>{if(event.target.matches('[data-sound]')&&['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(event.key)){event.preventDefault();const items=[...document.querySelectorAll('[data-sound]')];const direction=['ArrowDown','ArrowRight'].includes(event.key)?1:-1;const next=items[(items.indexOf(event.target)+direction+items.length)%items.length];next.focus();next.click();}});
let subdivision=2,beatsPerBar=4;
function renderAccentGrid(){const grid=document.querySelector('[data-accent-grid]');if(!grid)return;grid.innerHTML=Array.from({length:beatsPerBar},(_,b)=>`<div class="accent-beat"><span>${b+1}</span>${Array.from({length:subdivision},(_,s)=>{const state=b===0&&s===0?'accent':'on';const label=`Beat ${b+1}, click ${s+1}`;return `<button type="button" class="accent-cell" data-state="${state}" data-label="${label}" aria-label="${label}: ${state}. Tap to change."><i></i></button>`;}).join('')}</div>`).join('');}
function updateSubdivision(){document.querySelectorAll('[data-subdivision]').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.subdivision)===subdivision)));document.querySelector('[data-custom-subdivision]').value=subdivision;renderAccentGrid();}
const customSubdivision=document.querySelector('[data-custom-subdivision]');if(customSubdivision)customSubdivision.addEventListener('change',()=>{subdivision=Number(customSubdivision.value);updateSubdivision();});
document.querySelectorAll('[data-poly-count]').forEach(el=>el.addEventListener('change',()=>{const lane=document.querySelector(`[data-poly-lane="${el.dataset.polyCount}"]`);lane.innerHTML=Array.from({length:Number(el.value)},(_,i)=>`<button class="accent-cell" data-state="${i===0?'accent':'on'}" data-label="Rhythm ${el.dataset.polyCount}, pulse ${i+1}" aria-label="Rhythm ${el.dataset.polyCount}, pulse ${i+1}: ${i===0?'accent':'on'}. Tap to change."><i></i></button>`).join('');}));
function updateTrainingStatus(){const count=[...document.querySelectorAll('[data-trainer]')].filter(el=>el.getAttribute('aria-checked')==='true').length;document.querySelector('[data-training-status]').textContent=count?`${count} trainer${count===1?'':'s'} enabled`:'Metronome ready';}
function updateGap(){const click=Math.max(1,Math.min(16,Number(document.querySelector('[data-gap-click]').value)||2));const silent=Math.max(1,Math.min(16,Number(document.querySelector('[data-gap-silent]').value)||1));document.querySelector('[data-gap-summary]').textContent=`${click} bars with click · ${silent} silent`;document.querySelector('[data-gap-timeline]').innerHTML=`<span style="flex:${click}">${click} bars · click</span><span class="silent" style="flex:${silent}">${silent} ${silent===1?'bar':'bars'} · silent</span>`;}
document.querySelectorAll('[data-gap-click],[data-gap-silent]').forEach(el=>el.addEventListener('input',updateGap));
let context;let previewTimeout;
async function previewSound(name){const output=document.querySelector('[data-sound-status]');output.textContent=`Previewing ${name}…`;try{context ||= new (window.AudioContext||window.webkitAudioContext)();await context.resume();const volume=Number(document.querySelector('[data-volume]').value)/100;if(window.AUDIT_SAMPLES?.[name]){const sample=new Audio(window.AUDIT_SAMPLES[name]);sample.volume=volume;await sample.play();}else{const params={'Classic Click':[1000,.03,'square'],'Woodblock':[600,.05,'triangle'],'Soft Tone':[440,.06,'sine']}[name];const osc=context.createOscillator(),gain=context.createGain();osc.type=params[2];osc.frequency.value=params[0];gain.gain.setValueAtTime(Math.max(.00001,volume*.16),context.currentTime);gain.gain.exponentialRampToValueAtTime(.00001,context.currentTime+params[1]);osc.connect(gain);gain.connect(context.destination);osc.start();osc.stop(context.currentTime+params[1]);}clearTimeout(previewTimeout);previewTimeout=setTimeout(()=>output.textContent=`${name} preview finished`,900);}catch{output.textContent='Preview unavailable in this browser.';}}
const volume=document.querySelector('[data-volume]');if(volume)volume.addEventListener('input',()=>document.querySelector('[data-volume-value]').textContent=`${volume.value}%`);
const editions={maya:{name:'MAYA REED',product:'POCKET METRONOME',initials:'MR',accent:'#e7c58e',ink:'#251c10',title:'Find your<br>pocket.',description:'A daily metronome and three focused exercises from my practice room to yours.',by:'Maya Reed',pack:'The pocket<br>practice pack',note:'Keep the same feel when the click disappears. Let it come back to you.'},drums:{name:'DRUMS ONLY',product:'METRONOME',initials:'DO',accent:'#b1d5cb',ink:'#101c18',title:'Make every<br>beat count.',description:'A daily metronome and three focused exercises for a steadier sense of time.',by:'Drums Only',pack:'Your daily<br>practice pack',note:'Keep the same feel when the click disappears. Let it come back to you.'},eli:{name:'ELI PARK',product:'TIME / METRONOME',initials:'EP',accent:'#b7b5f3',ink:'#19172e',title:'Own your<br>time.',description:'A daily metronome and three focused exercises to bring your time into focus.',by:'Eli Park',pack:'The time<br>practice pack',note:'Keep the same feel when the click disappears. Let it come back to you.'}};
let edition='maya';
function setEdition(value){edition=value;const e=editions[value];app.style.setProperty('--accent',e.accent);app.style.setProperty('--accent-ink',e.ink);document.querySelectorAll('[data-edition-name]').forEach(el=>el.textContent=e.name);document.querySelectorAll('[data-edition-product]').forEach(el=>el.textContent=e.product);document.querySelectorAll('[data-initials]').forEach(el=>el.textContent=e.initials);document.querySelectorAll('[data-by]').forEach(el=>el.textContent=e.by);document.querySelectorAll('[data-welcome-title]').forEach(el=>el.innerHTML=e.title);document.querySelectorAll('[data-welcome-description]').forEach(el=>el.textContent=e.description);document.querySelectorAll('[data-pack-title]').forEach(el=>el.innerHTML=e.pack);document.querySelectorAll('[data-coach-note]').forEach(el=>el.textContent=e.note);}
function showCreator(view){app.dataset.creatorView=view;document.querySelectorAll('section[data-creator-view]').forEach(el=>el.hidden=el.dataset.creatorView!==view);}
const lessons=[{title:'The disappearing click',tempo:80,setup:'2 click bars / 1 silent bar',explain:'Gap Trainer',note:'Keep the same feel when the click disappears. Let it come back to you.'},{title:'Build speed without tension',tempo:80,setup:'80 → 120 BPM / +5 every 8 bars',explain:'Tempo Trainer',note:'Keep your shoulders loose. Only stay at a tempo if the notes still feel even.'},{title:'Change the grid, keep the pulse',tempo:90,setup:'1 → 2 → 3 → 4 clicks per beat',explain:'Subdivision Trainer',note:'The space between notes changes. The pulse underneath stays exactly the same.'}];
function openLesson(index){const l=lessons[index];document.querySelector('[data-lesson-title]').textContent=l.title;document.querySelector('[data-lesson-setup]').textContent=l.setup;document.querySelector('[data-lesson-type]').textContent=l.explain;document.querySelector('[data-coach-note]').textContent=l.note;setTempo(l.tempo);showCreator('lesson');setPlaying(false);}
const editionSelect=document.querySelector('[data-edition]');if(editionSelect){editionSelect.addEventListener('change',()=>setEdition(editionSelect.value));setEdition('maya');showCreator('welcome');}
const requestedEdition=new URLSearchParams(location.search).get('edition');if(editions[requestedEdition]){setEdition(requestedEdition);if(editionSelect)editionSelect.value=requestedEdition;}
renderAccentGrid();
window.addEventListener('pagehide',()=>{clearInterval(timer);context?.close();});
